version: 1
disable_existing_loggers: false

formatters:
  minimal:
    format: "%(message)s"
  standard:
    format: "%(asctime)s - %(levelname)s - [%(name)s] - %(message)s"
  detailed:
    format: "%(asctime)s - %(levelname)s — [%(name)s:%(filename)s:%(funcName)s:%(lineno)d] - %(message)s"
  error:
    format: "%(asctime)s - %(levelname)s - [<PID %(process)d:%(processName)s> %(name)s:%(filename)s:%(funcName)s:%(lineno)d] -  %(message)s"

handlers:
  console_rich_handler:
    class: rich.logging.RichHandler
    level: INFO
    formatter: standard
    rich_tracebacks: True
    markup: true 

  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    # ext://interpret the stream name as a Python logging extension, rather than a literal stream name
    stream: ext://sys.stdout

  file_handler:
    # logging.FileHandler
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    # prefix: experiments/snapshots/project-template/reporting/logs/
    # alternatively send files to different filenames based on level
    filename: report.log
    # 10 MB
    maxBytes: 10485760
    backupCount: 10
    encoding: utf-8
    mode: a

root:
  level: INFO
  handlers: [console_rich_handler,file_handler]
  propogate: yes


# loggers:
#   <module>:
#     level: ERROR
#     handlers: [console_rich_handler,file_handler]
#     propagate: no

#   <module.x>:
#     level: ERROR
#     handlers: [console_rich_handler,file_handler]
#     propagate: no
